<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="FirstAttemptQdrantMigrator.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="Qdrant.Client" />
    <PackageReference Include="System.Linq.Async" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Florio.VectorEmbeddings\Florio.VectorEmbeddings.csproj" />
  </ItemGroup>
</Project>